# Generated by Django 6.0.6 on 2026-07-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesetting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 1200x630px. Used as the thumbnail when your site link is shared.', null=True, upload_to='og_images/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_description',
            field=models.CharField(blank=True, help_text='Shown as the description in link previews (WhatsApp, Facebook, Telegram, etc.)', max_length=300),
        ),
    ]
